name: core-tests

on:
  push:
    paths:
      - 'packages/core/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'packages/core/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run core tests
        working-directory: packages/core
        run: bun test
